# Code Rabbit  Automated Code Reviews
language: "en-US"
early_access: false
reviews:
  request_changes_workflow: true
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
    drafts: false
chat:
  auto_reply: true
base_branches:
  - "main"
  - "dev"
# path_filters:
#   - !**/.git/**
#   - !**/generated/**
